# spring.application.name=demo

spring:
  kafka:
    producer:
      # Kafka ????? ?? ??
      bootstrap-servers: localhost:9092
      acks: all
      # Kafka ???? key? ???? ? ??? ???? ??
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: MANUAL_IMMEDIATE
      type: SINGLE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: dev-group # ??